## Dragon Real Estate - Price Predictor

In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [2]:
housing = pd.read_csv("data.csv")

In [3]:
housing.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64  
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64  
 9   tax      506 non-null    int64  
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['chas'].value_counts()

chas
0    471
1     35
Name: count, dtype: int64

In [6]:
housing.describe()

crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.288858   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704186   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.211000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.629000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
"""%matplotlib inline
housing.hist(bins=50,figsize=(20,15))"""

'%matplotlib inline\nhousing.hist(bins=50,figsize=(20,15))'

## Train-Test Splitting

In [8]:
"""def split_train_test(data,test_ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    print(shuffled)
    test_set_size=int (len(data)* test_ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size : ]
    return data.iloc[train_indices],data.iloc[test_indices]"""

'def split_train_test(data,test_ratio):\n    np.random.seed(42)\n    shuffled = np.random.permutation(len(data))\n    print(shuffled)\n    test_set_size=int (len(data)* test_ratio)\n    test_indices = shuffled[:test_set_size]\n    train_indices = shuffled[test_set_size : ]\n    return data.iloc[train_indices],data.iloc[test_indices]'

In [9]:
#train_set ,test_set = split_train_test(housing,0.2)

In [10]:
#print(f"Rows in train set : {len(train_set)}\nRows in test set :{len(test_set)}\n")

In [11]:
from sklearn.model_selection import train_test_split
train_set ,test_set=train_test_split(housing,test_size=0.2,random_state=42)
print(f"Rows in train set : {len(train_set)}\nRows in test set :{len(test_set)}\n")

Rows in train set : 404
Rows in test set :102



In [12]:
from sklearn.model_selection import StratifiedShuffleSplit
spilt = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index, test_index in spilt.split(housing, housing['chas']):
    strat_train_set =housing.loc[train_index]
    strat_test_set=housing.loc[test_index]


In [13]:
housing=strat_train_set.copy()

In [14]:
strat_train_set.describe()

crim          zn       indus        chas         nox          rm  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.284347   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.714370   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.217500   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.632000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat        medv  
count  404.000000  404.000000  
mean    12.791609   22.509406  
std      7.235740    9.385531  
min      1.730000    5.000000  
25%      6.847500   16.600000  
50%     11.570000   21.150000  
75%     17.102500   25.000000  
max     36.980000   50.000000

In [15]:
strat_train_set['chas'].value_counts()

chas
0    376
1     28
Name: count, dtype: int64

## Looking for correletions

In [16]:
corr_matrix = housing.corr()
corr_matrix['medv'].sort_values(ascending=False)

medv       1.000000
rm         0.678575
b          0.361761
zn         0.339741
dis        0.240451
chas       0.205066
age       -0.364596
rad       -0.374693
crim      -0.393715
nox       -0.422873
tax       -0.456657
indus     -0.473516
ptratio   -0.493534
lstat     -0.740494
Name: medv, dtype: float64

In [17]:
# 1 means strong correlations

In [18]:
#from pandas.plotting import scatter_matrix
#attributes =["medv","rm","zn","lstat"]
#scatter_matrix(housing[attributes],figsize=(12,8))

In [19]:
#housing.plot(kind='scatter',x='rm',y='medv',alpha=0.5)

In [20]:
#housing.plot(kind='scatter',x='lstat',y='medv',alpha=0.5)

## Trying out Attribute combinations 

In [21]:
housing['TAXRM']=housing['tax']/housing['rm']

In [22]:
#housing.plot(kind='scatter',x='TAXRM',y='medv',alpha=0.5)#REMOVE OUTLIER

In [23]:
housing = strat_train_set.drop("medv" , axis=1)
housing_labels = strat_train_set["medv"].copy()

## Handling MISSING values

In [24]:
housing.describe()

crim          zn       indus        chas         nox          rm  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.284347   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.714370   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.217500   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.632000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [25]:
#rm value are missing .To take care of missing values ,Three options
#1.Get rid of missing data points
#2.Get rid of whole attribute
#3.Mean imputation,meadian imputaions

In [26]:
#drop values
a=housing.dropna(subset=["rm"]).shape
#a.shape

In [27]:
housing.drop("rm",axis=1).shape
#rm caloum get dropped and originalhousing data will not get changed 

(404, 12)

In [28]:
median=housing['rm'].median()

In [29]:
#Option 3
housing["rm"].fillna(median)
#originalhousing data will not get changed and if you want to change set implace= true

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: rm, Length: 404, dtype: float64

In [30]:
housing.describe()

crim          zn       indus        chas         nox          rm  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.284347   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.714370   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.217500   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.632000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [31]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [32]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21750e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [33]:
imputer.statistics_.shape

(13,)

In [34]:
x= imputer.transform(housing)

In [35]:
housing_tr = pd.DataFrame(x,columns=housing.columns)

In [36]:
housing_tr.describe()
#we have imputed median and fitted into our data

crim          zn       indus        chas         nox          rm  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.283686   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.710847   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.879750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.217500   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio           b  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            lstat  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Scikit-learn Design

Primarily 3 types of objects 
1. Estimators - ex : Imputer- It has fit method and transform method.  Fit - fits in dataset and calculates internal parameters

2. Transforms transform - it takes input and returns transformed output. fit_transform() method 

3. Predictors : Linear Regression ,KNN. Two funstions:-fit(),predict(), score function

## Feature Scaling 

Primarily ,Two types of scaling methods :
1. Min-max Scaling (Normalization) /z
    =(value - min)/(max - min) (...range is 0 to 1)
    SKlearn class MinMaxScaler

2. Standardization
    (value - mean)/std 
     sklearn class Standard Scalar 


## Creating a Pipeline
Everything that we have done earlier i.e. imputaion etc should be done here 

In [37]:
from sklearn.pipeline import Pipeline

from sklearn.preprocessing import StandardScaler
my_pipeline =Pipeline([
     ('imputer',SimpleImputer(strategy="median")),
    ('std_scaler',StandardScaler()),
    #............add as many you want 
])


In [38]:
housing_num_tr = my_pipeline.fit_transform(housing)
housing_num_tr

array([[-0.43942006,  3.12628155, -1.12165014, ..., -0.97491834,
         0.41164221, -0.86091034],
       [-0.44352175,  3.12628155, -1.35893781, ..., -0.69277865,
         0.39131918, -0.94116739],
       [ 0.15682292, -0.4898311 ,  0.98336806, ...,  0.81196637,
         0.44624347,  0.81480158],
       ...,
       [-0.43525657, -0.4898311 , -1.23083158, ..., -0.22254583,
         0.41831233, -1.27603303],
       [ 0.14210728, -0.4898311 ,  0.98336806, ...,  0.81196637,
        -3.15239177,  0.73869575],
       [-0.43974024, -0.4898311 ,  0.37049623, ..., -0.97491834,
         0.41070422,  0.09940681]])

In [39]:
housing_num_tr.shape

(404, 13)

## Selecting a desired model for Dragon Real Estates

In [40]:
from sklearn.linear_model import LinearRegression
#model = LinearRegression()
from sklearn.tree import DecisionTreeRegressor
#model = DecisionTreeRegressor()
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(housing_num_tr, housing_labels)

RandomForestRegressor()

In [41]:
some_data = housing.iloc[:5]

In [42]:
some_labels = housing_labels.iloc[:5]

In [43]:
prepared_data = my_pipeline.transform(some_data)

In [44]:
model.predict(prepared_data)

array([22.397, 25.499, 16.602, 23.302, 23.467])

In [45]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## Evaluating the model using RMSE

In [46]:
from sklearn.metrics import mean_squared_error
housing_predictions = model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels, housing_predictions)
rmse = np.sqrt(mse)

mse # very high error 2.Overfitting cause train set is exposed and model had learn it

In [47]:
rmse

1.2533465894425708

## Using Cross validation to overcome overfitting problem

1. K-fold Cross validation

In [48]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr ,housing_labels, scoring ="neg_mean_squared_error",cv=10)
rmse_score = np.sqrt(-scores)

In [49]:
rmse_score

array([2.74344   , 2.96947292, 4.40856679, 2.83184097, 3.75784619,
       2.56409967, 4.75943302, 3.35278775, 3.14877404, 3.23820042])

Decision tree is working better 

In [50]:
def print_scores(scores):
    print("Scores : ",scores)
    print("Mean: ",scores.mean())
    print("Standard_deviation : ",scores.std())

In [51]:
print_scores(scores)

Scores :  [ -7.52646305  -8.81776941 -19.43546117  -8.01932327 -14.12140798
  -6.5746071  -22.6522027  -11.24118567  -9.91477795 -10.48594197]
Mean:  -11.8789140277439
Standard_deviation :  5.057127449924093


## Saving the model

In [52]:
from joblib import dump, load
dump(model, 'Dragon.joblib')

['Dragon.joblib']

## Testing the model on test data

In [58]:
x_test = strat_test_set.drop("medv", axis=1)
y_test =strat_test_set["medv"].copy()
x_test_prepared = my_pipeline.transform(x_test)
final_predictions = model.predict(x_test_prepared)
final_mse = mean_squared_error(y_test, final_predictions)
final_rmse = np.sqrt(final_mse)
#print(final_predictions,list(y_test)) it is very good outcome

[24.816 11.395 25.337 21.461 18.077 14.98  19.824 14.35  31.389 41.828
 19.681 11.606 25.481 25.442 19.65  11.306 32.018 14.157 23.846 17.928
 20.198 17.641 17.425 21.757 18.763 31.244 16.468 32.877  8.644 33.19
 24.063 21.458 23.019 10.838 20.902 10.942 43.034 24.318 23.131 41.035
 23.911 29.029 20.452 20.921 19.243 33.193 44.422 20.178 20.51  21.758
 21.595 14.387 21.223 15.016 25.029 32.972 43.888 29.133 19.465 20.865
 46.402  9.996 19.44  24.951 14.943 32.613 19.394 18.577 19.109 33.566
 26.943 22.74  21.871 22.536 34.627 12.891 15.909 20.12  20.888 21.504
 22.537 20.842 13.817 22.755 21.245 21.208 13.382 21.399 21.879 22.954
 18.944 26.913  7.561 27.186 19.604 29.294 19.367 31.121 14.897 26.606
 21.048 20.038] [16.5, 10.2, 30.1, 23.0, 14.4, 15.6, 19.4, 14.1, 30.3, 35.2, 23.1, 13.8, 25.0, 27.9, 19.5, 12.3, 32.2, 13.5, 23.8, 21.7, 19.2, 19.5, 10.4, 23.2, 18.6, 28.5, 15.2, 32.0, 7.2, 34.6, 20.1, 20.6, 23.6, 13.1, 23.8, 12.7, 43.1, 24.7, 22.2, 44.0, 28.1, 31.0, 21.7, 23.4, 19.5, 33.1,

In [59]:
final_rmse

2.9460423003232843

In [60]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24745608, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

## Using the model

In [61]:
from joblib import dump ,load
import numpy as np
model = load('Dragon.joblib')

In [62]:
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24745608, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(features)

array([22.397])